package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.gitlabEEConnection
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            gitlabEEConnection {
                id = "PROJECT_EXT_6"
                displayName = "GitLab CE/EE"
                serverUrl = "https://gitlab.bringauto.com/"
                applicationId = "18597964ea6e7fca2ef39ebcfd978a0af75c0b8312a3a1965444468ce57ef3c2"
                clientSecret = "credentialsJSON:fd526218-7494-4fa2-8bed-d534fa14e18a"
            }
        }
    }
}
