package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'AnotherProject_HttpsGithubComHofin34testingCpp'
in the project with id = 'AnotherProject', and delete the patch script.
*/
create(RelativeId("AnotherProject"), GitVcsRoot({
    id("AnotherProject_HttpsGithubComHofin34testingCpp")
    name = "https://github.com/hofin34/testing_cpp"
    url = "https://github.com/hofin34/testing_cpp"
    branch = "refs/heads/main"
}))

