package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'MyGitRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("MyGitRoot")) {
    val expected = GitVcsRoot({
        id("MyGitRoot")
        name = "https://github.com/bringauto/youtrack-test-repo#refs/heads/master"
        url = "https://github.com/bringauto/youtrack-test-repo"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = password {
            userName = "hofin34"
            password = "zxx8a7c097df17b0feae4a77d74fd19e6f6"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "hofin34"
            password = "credentialsJSON:ff26f64d-bcd8-4372-88ff-6579c5c713bb"
        }
    }

}
